"""
Real-Time SMS Spam Detection — Streamlit App
=============================================
Run:
    streamlit run app/app.py

Requires:
    - models/vectorizer.pkl
    - models/best_model.pkl

Both files are generated by running notebooks/spam_detection.ipynb first.
"""

import re
import joblib
import nltk
import streamlit as st
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# ---------------------------------------------------------------------------
# One-time NLTK downloads (silent if already present)
# ---------------------------------------------------------------------------
nltk.download("punkt", quiet=True)
nltk.download("punkt_tab", quiet=True)
nltk.download("stopwords", quiet=True)

STOP_WORDS = set(stopwords.words("english"))


# ---------------------------------------------------------------------------
# Text cleaning — must mirror the preprocessing used during training
# ---------------------------------------------------------------------------
def clean_text(text: str) -> str:
    """Lowercase, remove punctuation/numbers, strip stopwords."""
    text = text.lower()
    text = re.sub(r"[^a-z\s]", "", text)       # remove punctuation & numbers
    tokens = word_tokenize(text)                 # tokenise
    tokens = [t for t in tokens if t not in STOP_WORDS and len(t) > 1]
    return " ".join(tokens)


# ---------------------------------------------------------------------------
# Load saved model & vectorizer (cached so they load only once per session)
# ---------------------------------------------------------------------------
@st.cache_resource
def load_artifacts():
    vectorizer = joblib.load("models/vectorizer.pkl")
    model = joblib.load("models/best_model.pkl")
    return vectorizer, model


# ---------------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="SMS Spam Detector",
    page_icon="📱",
    layout="centered",
)

st.title("📱 Real-Time SMS Spam Detector")
st.markdown(
    "Enter an SMS message below and the model will classify it as **Ham** (legitimate) "
    "or **Spam** in real time."
)

st.divider()

# ---------------------------------------------------------------------------
# Sidebar — about section
# ---------------------------------------------------------------------------
with st.sidebar:
    st.header("ℹ️ About")
    st.markdown(
        """
        **Model:** Best of Multinomial NB / Linear SVM  
        **Features:** TF-IDF (unigrams + bigrams, max 5 000 features)  
        **Dataset:** UCI SMS Spam Collection (~5 572 messages)  

        **Team**  
        - Abdul Rafay (B24S0348AI074)  
        - Farooq Awan (B24S0960AI065)  

        *ML Lab — Mr Waqas Yousaf*
        """
    )
    st.divider()
    st.subheader("🧪 Quick Test Messages")
    example_spam = "Congratulations! You've won a FREE prize. Call now: 0800-123456"
    example_ham  = "Hey, are we still meeting at 6 pm tonight?"
    if st.button("Load spam example"):
        st.session_state["user_input"] = example_spam
    if st.button("Load ham example"):
        st.session_state["user_input"] = example_ham

# ---------------------------------------------------------------------------
# Main input area
# ---------------------------------------------------------------------------
user_input = st.text_area(
    label="✉️ SMS Message",
    value=st.session_state.get("user_input", ""),
    height=150,
    placeholder="Type or paste an SMS message here…",
)

predict_btn = st.button("🔍 Classify Message", use_container_width=True)

# ---------------------------------------------------------------------------
# Prediction
# ---------------------------------------------------------------------------
if predict_btn:
    if not user_input.strip():
        st.warning("Please enter a message before classifying.")
    else:
        try:
            vectorizer, model = load_artifacts()
        except FileNotFoundError:
            st.error(
                "Model files not found. "
                "Please run `notebooks/spam_detection.ipynb` first to generate "
                "`models/vectorizer.pkl` and `models/best_model.pkl`."
            )
            st.stop()

        cleaned = clean_text(user_input)
        features = vectorizer.transform([cleaned])
        prediction = model.predict(features)[0]   # 0 = ham, 1 = spam

        st.divider()

        if prediction == 1:
            st.error("🔴 **SPAM** — This message looks like spam.", icon="🚨")
        else:
            st.success("🟢 **HAM** — This message looks legitimate.", icon="✅")

        # Confidence / decision score ----------------------------------------
        st.subheader("Model Confidence")

        if hasattr(model, "predict_proba"):
            # Naive Bayes and calibrated models expose probability estimates
            proba = model.predict_proba(features)[0]
            ham_prob, spam_prob = proba[0], proba[1]
            st.progress(int(spam_prob * 100), text=f"Spam probability: {spam_prob:.1%}")
            col1, col2 = st.columns(2)
            col1.metric("Ham probability",  f"{ham_prob:.1%}")
            col2.metric("Spam probability", f"{spam_prob:.1%}")
        else:
            # LinearSVC — use the signed distance from the decision boundary
            score = model.decision_function(features)[0]
            # Positive score → spam, negative → ham
            st.info(
                f"Decision score: **{score:.3f}**  \n"
                "(positive = spam side, negative = ham side of the hyperplane)"
            )

        # Show cleaned text for transparency ------------------------------------
        with st.expander("🔎 Preprocessed input sent to the model"):
            st.code(cleaned if cleaned else "(empty after cleaning)")

st.divider()
st.caption("BSAI Blue — Machine Learning Lab Project · Abdul Rafay & Farooq Awan")
